blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/SalesforceAIResearch/uni2ts/discussions
    about: Use GitHub Discussions to ask and answer questions, exchange ideas, and share learning.